datasets:
  
  # ELEVATION AND GEOMETRY DATASETS
  measures_bedmachine_antarctica:
    display_name: BedMachine Antarctica
    path: /g/data/av17/access-nri/cryosphere-data-pool/elevation_geometry/measures_bedmachine_antarctica
    description: High-resolution bed topography and ice thickness data for Antarctica.
    tags:
      - antarctica
      - bed topography
      - ice thickness
      - surface elevation
      - bed uncertainty
      - ice mask
    extension: nc
  
  bedmap:
    display_name: Bedmap
    path: /g/data/av17/access-nri/cryosphere-data-pool/elevation_geometry/bedmap
    description: Gridded, geospatial, and point datasets of Antarctic ice thickness, surface elevation, and bed elevation.
    tags:
      - antarctica
      - bed topography
      - ice thickness
      - surface elevation
    subdatasets:
      v1:
        geospatial:
          subpath: geospatial_data
          extension: gpkg
          no_data_value: -9999
        points:
          subpath: point_data
          extension: csv
          skip_lines: 18
          no_data_value: -9999
        gridded:
          subpath: gridded_data
          extension: tif
      v2:
        geospatial:
          subpath: geospatial_data
          extension: gpkg
          no_data_value: -9999
          ignore_dirs:
            - shapeLines
        points:
          subpath: point_data
          extension: csv
          skip_lines: 18
          no_data_value: -9999
        gridded:
          subpath: gridded_data
          extension: tif
          ignore_dirs:
            - resources
      v3:
        geospatial:
          subpath: geospatial_data
          extension: gpkg
          no_data_value: -9999
          ignore_dirs:
            - shapeLines
        points:
          subpath: point_data
          extension: csv
          skip_lines: 18
          no_data_value: -9999
        gridded:
          subpath: gridded_data
          extension: nc
          ignore_dirs:
            - bm3_streamlines_pt

  measures_its_live_antarctica_annual_ice_mask:
    display_name: ITS_LIVE Annual 240 m Ice Sheet Extent Mask - 1997 to 2021
    path: /g/data/av17/access-nri/cryosphere-data-pool/elevation_geometry/measures_its_live_antarctic_annual_240m_ice_sheet_extent_masks_1997_2021
    description: Annual ice sheet extent masks for Antarctica from ITS_LIVE at 240 m resolution, covering the years 1997 to 2021. Ice thickness and velocity data used to determine the presence of ice are also provided.
    tags:
      - antarctica
      - ice mask
      - ice thickness
      - ice velocity
    extension: nc

  measures_its_live_antarctic_grounded_ice_sheet_elevation_change:
    display_name: ITS_LIVE Antarctic Ice Sheet grounded ice elevation change
    path: /g/data/av17/access-nri/cryosphere-data-pool/elevation_geometry/measures_its_live_antarctic_grounded_ice_sheet_elevation_change
    description: ITS_LIVE Antarctic Ice Sheet grounded ice elevation change
    tags:
      - antarctica
      - ice thickness
      - thickness change
    extension: nc

  measures_its_live_antarctic_quarterly_ice_shelf_height_change:
    display_name: ITS_LIVE Antarctic Ice Shelf quarterly height change and basal melt rates - 1992 to 2017
    path: /g/data/av17/access-nri/cryosphere-data-pool/elevation_geometry/measures_its_live_antarctic_quarterly_1920m_ice_shelf_height_change_and_basal_melt_rates_1992_2017
    description: ITS_LIVE Antarctic Ice Shelf quarterly height change and basal melt rates - 1992 to 2017
    tags:
      - antarctica
      - ice shelf
      - height change
      - basal melt rates
      - smb
      - ice thickness
    extension: nc

  # GEOSPTATIAL DATASETS
  measures_antarctic_boundaries:
    display_name: Antarctic Boundaries for IPY 2007-2009 from Satellite Radar
    path: /g/data/av17/access-nri/cryosphere-data-pool/geospatial/measures_antarctic_boundaries_for_ipy_2007_2009_from_satellite_radar
    description: Antarctic coastline, grounding line, and ice front positions derived from satellite radar data for the International Polar Year 2007-2009.
    tags:
      - antarctica
      - coastline
      - grounding line
      - ice front
      - ice mask
    extension: shp
    subdatasets:
      v1:
        coastline:
          subpath: Coastline_Antarctica
        grounding_line:
          subpath: GroundingLine_Antarctica
        ice_boundaries:
          subpath: IceBoundaries_Antarctica
        ice_shelf:
          subpath: IceShelf_Antarctica
        mask:
          subpath: Mask_Antarctica
          extension: tif
      v2:
        basins:
          subpath: Basins_Antarctica
        basins_imbie:
          subpath: Basins_IMBIE_Antarctica
        coastline:
          subpath: Coastline_Antarctica
        grounding_line:
          subpath: GroundingLine_Antarctica
        ice_boundaries:
          subpath: IceBoundaries_Antarctica
        ice_shelf:
          subpath: IceShelf_Antarctica
        mask:
          subpath: Mask_Antarctica
          extension: tif

  measures_antarctic_grounding_line:
    display_name: Antarctic Grounding Line from Differential Satellite Radar Interferometry
    path: /g/data/av17/access-nri/cryosphere-data-pool/geospatial/measures_antarctic_grounding_line_from_differential_satellite_radar_interferometry
    description: Grounding line positions for Antarctica derived from differential satellite radar interferometry.
    tags:
      - antarctica
      - grounding line
    extension:
      v1: csv
      v2: shp

  # BASAL FORCING DATASETS
  antarctic_geothermal_heat_flow_model_aq1:
    display_name: Antarctic Geothermal Heat Flow Model AQ1
    path: /g/data/av17/access-nri/cryosphere-data-pool/basal_forcing/antarctic_geothermal_heat_flow_model_aq1
    description: Geothermal heat flow model for Antarctica (AQ1) providing estimates of basal heat flux beneath the Antarctic ice sheet.
    tags:
      - antarctica
      - geothermal heat flow
    extension: nc
    subdatasets:
      v1:
        20km:
          subpath: 20km
        50km:
          subpath: 50km