name: Release access-cryosphere-data-pool

on:
  push:
    tags:
      - 'v*'
jobs:
  publish_python_package:
    uses: access-nri/actions/.github/workflows/publish-python-package.yml@main
    with:
      pypi-package: true
      conda-package: true
    secrets: inherit
    permissions:
      actions: write
  
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish_python_package

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ needs.publish_python_package.outputs.artifact-name }}
          path: dist

      - name: Create Release
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 #v2.3.3
        with:
          tag_name: ${{ github.ref_name }}
          name: access-cryosphere-data-pool ${{ github.ref_name }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            dist/*